name: build and test
on:
  [push, pull_request, workflow_dispatch, workflow_call]
jobs:
  build-and-test:
    runs-on: ${{matrix.os}}
    #permette l'esecuzione del workflow su tre sistemi operativi diversi,
    #per assicurare il corretto funzionamento del progetto su so diversi
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      #checkout del progetto sulla macchina locale di github
      - uses: actions/checkout@v3
      #installo node sulla macchina locale di github
      - name: ${{matrix.os}} - Node.js setup
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: ${{matrix.os}} - Build Project
        run: |
          npm ci
          npm run build
      - name: ${{matrix.os}} - Execute project tests
        run: npm run test