name: main
on:
  [push, workflow_dispatch]
jobs:
  build-and-test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: ${{matrix.os}} - Node.js setup
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: ${{matrix.os}} - Build Project
        run: |
          npm ci
          npm run build
      - name: ${{matrix.os}} - Execute project tests
        run: npm run test