name: main
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: |
          npm ci
          npm run build
  tests: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Project tests 
        run: npm run test
