name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  testing:
  
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: ${{matrix.os}} - install dependencies
        run: npm ci

      - name: ${{matrix.os}} - build project
        run: npm run build

      - name: ${{matrix.os}} - execute tests
        run: npm run test
    
    
    
  pushing:
    needs: testing
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v3

      - name: pushing to release
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          create_branch: true
          branch: release
          
    
    
